"""empty message

Revision ID: 54594d1f42b0
Revises: 0c4b5b5d8a58
Create Date: 2025-05-08 15:39:55.033885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54594d1f42b0'
down_revision = '0c4b5b5d8a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_created_at')
        batch_op.drop_index('ix_conversation_prediction')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_created_at')
        batch_op.drop_index('ix_user_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_prediction', ['prediction'], unique=False)
        batch_op.create_index('ix_conversation_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
