"""Add User model

Revision ID: bd4fbc41753e
Revises: 54594d1f42b0
Create Date: 2025-05-08 19:52:17.336249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd4fbc41753e'
down_revision = '54594d1f42b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_created_at')
        batch_op.drop_index('ix_conversation_prediction')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_index('ix_user_created_at')
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_users_created_at')
        batch_op.drop_index('ix_users_username')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_index('ix_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_created_at', ['created_at'], unique=False)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_prediction', ['prediction'], unique=False)
        batch_op.create_index('ix_conversation_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
